apiVersion: v1
kind: Service
metadata:
  name: learning-journey
  labels:
    app: learning-journey
spec:
  type: NodePort
  ports:
  - name: '8000'
    port: 8000
    targetPort: 3000
  selector:
    app: learning-journey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-journey
  labels:
    app: learning-journey
spec:
  selector:
    matchLabels:
      app: learning-journey
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: learning-journey
    spec:
      containers:
      - name: learning-journey
        image: harbor-test.app.gittigidiyor.net/gg/learning-journey:3
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 1152Mi
            cpu: '1'
        volumeMounts:
        - mountPath: /var/log/java
          name: learning-journey-claim0
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
      - name: learning-journey-claim0
        emptyDir: {}
