apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-journey
  labels:
    app: learning-journey
spec:
  selector:
    matchLabels:
      app: learning-journey
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: learning-journey
    spec:
      containers:
      - name: learning-journey
        image: harbor-test.app.gittigidiyor.net/gg/learning-journey:%%IMAGE_VERSION%%
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 1152Mi
            cpu: '1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 10