apiVersion: v1
kind: Service
metadata:
  name: learning-journey
  labels:
    app: learning-journey
spec:
  type: NodePort
  ports:
  - name: '8000'
    port: 8000
    targetPort: 3000
  selector:
    app: learning-journey